### ISSUE TITLE
Timestamp column `ts` seems to be hardcoded?

### ISSUE THREAD

**Issue by vbmithr** [GreptimeTeam/greptimedb-client-go#79]
I get

```
rpc error: code = Internal desc = Invalid InsertRequest, reason: Expecting insert data to be presented on a not null or no default value column 'lts'.
```

Whenever I create a table with a time index column not named `ts`, inserting data do not work.

**Comment by yuanbohan** [comment]
hi, sorry for the inconvenience, but you can [SetTimestampAlias](https://pkg.go.dev/github.com/GreptimeTeam/greptimedb-client-go#Metric.SetTimestampAlias) as you need.

By the way, there is no need to create the table via schema in advance, it will be created automatically and the data type will match.

And greptimedb-client-go is planned to adjust to the new version of [proto](https://github.com/GreptimeTeam/greptime-proto), and it will behave better thereafter.
